site_name: "Soundscapy"
site_url: https://soundscapy.readthedocs.io/en/latest/
site_dir: site
site_author: "Andrew Mitchell"
site_description: "Documentation website for Soundscapy"
repo_name: "MitchellAcoustics/Soundscapy"
repo_url: https://github.com/MitchellAcoustics/Soundscapy
copyright: Copyright &copy; 2025 Andrew Mitchell

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Home: index.md
  - About:
      - "License": license.md
  - Tutorials:
      - tutorials/index.md
      - "Quick Start": tutorials/QuickStart.md
      - "Quick Start pt. 2": tutorials/0_QuickStart_for_Beginners.md
      - "Understanding Soundscape Analysis": tutorials/1_Understanding_Soundscape_Analysis.md
      - "Working with Soundscape Survey Data": tutorials/2_Working_with_Soundscape_Survey_Data.md
      - "Advanced Visualization Techniques": tutorials/3_Advanced_Visualization_Techniques.md
      - "The Soundscape Perception Index (SPI)": tutorials/SoundscapePerceptionIndex-SPI.md
      - "Using Soundscapy for Binaural Recording Analysis": tutorials/BinauralAnalysis.md
      - "How To Analyse and Represent Soundscape Perception": tutorials/HowToAnalyseAndRepresentSoundscapes.md
  - Reference:
      - Overview: reference/index.md
      - Soundscapy: reference/soundscapy.md
      - Surveys: reference/surveys.md
      - Databases: reference/databases.md
      - Plotting:
          - reference/plotting/index.md
          - "ISO Plot": reference/plotting/iso_plot.md
          - "Plot Functions": reference/plotting/plot_functions.md
          - "Likert": reference/plotting/likert.md
          - "Parameter Models": reference/plotting/param_models.md
          - "Parameter Defaults": reference/plotting/defaults.md
          - "Plotting Context": reference/plotting/plot_context.md
      - Audio:
          - reference/audio/index.md
          - "Binaural": reference/audio/binaural.md
          - "Audio Analysis": reference/audio/audio_analysis.md
          - "Metrics": reference/audio/metrics.md
          - "Parallel Processing": reference/audio/parallel_processing.md
      - SPI: reference/spi.md
      - SATP: reference/satp.md
      - Logging: reference/logging.md
  - Developer:
      - Overview: developer/index.md
      - "Plotting Internals": developer/plotting-internals.md
      - "R Internals": developer/r-internals.md
      - Utilities: developer/utilities.md
  - "News":
      - news.md
      - "Changelog": CHANGELOG.md

theme:
  name: material
  #  logo: img/DarkLogo.png
  features:
    - content.action.view
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.prune
    - navigation.top
    - content.action.edit
    - content.code.copy
    - content.tooltips
  font:
    code: Fira Code
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: lucide/sun-moon
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: lucide/sun
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: lucide/moon
        name: Switch to system preference

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - stylesheets/extra.css

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            extensions:
              - griffe_fieldz:
                  include_inherited: true
                  include_private: false
                  add_fields_to: docstring-attributes
                  remove_fields_from_members: false
                  strip_annotated: false
            docstring_section_style: spacy
            docstring_style: "numpy"
            members_order: source
            separate_signature: true
            show_if_no_docstring: false
            merge_init_into_class: true
            overloads_only: true
            show_overloads: true
            show_root_heading: true
            show_signature: true
            show_signature_annotations: true
            show_signature_type_parameters: true
            show_source: true
            show_submodules: true
            show_symbol_type_heading: true # waiting for general release
            show_symbol_type_toc: true
            modernize_annotations: true
            summary: true
          inventories:
            - "https://docs.python.org/3/objects.inv"

markdown_extensions:
  - admonition
  - pymdownx.tasklist
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/MitchellAcoustics"
