# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: "Soundscapy"
site_url: https://soundscapy.readthedocs.io/en/latest/
site_dir: site
site_author: "Andrew Mitchell"
site_description: "Documentation website for Soundscapy"
repo_name: "MitchellAcoustics/Soundscapy"
repo_url: https://github.com/MitchellAcoustics/Soundscapy
copyright: Copyright &copy; 2025 Andrew Mitchell

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Home: index.md
  - About:
      - "License": license.md
  - Tutorials:
      - tutorials/index.md
      - "Quick Start": tutorials/QuickStart.ipynb
      - "How To Analyse and Represent Soundscape Perception": tutorials/HowToAnalyseAndRepresentSoundscapes.ipynb
      - "The Soundscape Perception Index (SPI)": tutorials/SoundscapePerceptionIndex-SPI.ipynb
      - "Using Soundscapy for Binaural Recording Analysis": tutorials/BinauralAnalysis.ipynb
  - "API reference":
      - "Core": reference/api.md
      - "Survey Analysis": reference/surveys.md
      - "Plotting":
          - reference/plotting.md
          - reference/plotting/backends.md
      - "Soundscape Perception Index (SPI)": reference/spi.md
      - "Binaural Analysis": reference/audio.md
      - "Databases": reference/databases.md
  - "News":
      - news.md
      - "Changelog": CHANGELOG.md

theme:
  name: material
  #  logo: img/DarkLogo.png
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - navigation.top
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [.]
          options:
            docstring_section_style: spacy
            docstring_style: "numpy"
            separate_signature: true
            show_if_no_docstring: false
            merge_init_into_class: true
            show_symbol_type_heading: true # waiting for general release
            show_symbol_type_toc: true
            modernize_annotations: true
            summary: true
          inventories:
            - "https://docs.python.org/3/objects.inv"
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"
  - mkdocs-jupyter:
      include_source: true
      theme: default
#        execute: true

markdown_extensions:
  - admonition
  - pymdownx.tasklist
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/MitchellAcoustics"
