[project]
nav = [
    { "Home" = "index.md" },
    { "Tutorials" = [
        "tutorials/index.md",
        { "Quick Start" = "tutorials/rendered/QuickStart.md" },
        { "Quick Start pt. 2" = "tutorials/rendered/0_QuickStart_for_Beginners.md" },
        { "Understanding Soundscape Analysis" = "tutorials/rendered/1_Understanding_Soundscape_Analysis.md" },
        { "Working with Soundscape Survey Data" = "tutorials/rendered/2_Working_with_Soundscape_Survey_Data.md" },
        { "Advanced Visualization Techniques" = "tutorials/rendered/3_Advanced_Visualization_Techniques.md" },
        { "The Soundscape Perception Index (SPI)" = "tutorials/rendered/SoundscapePerceptionIndex-SPI.md" },
        { "Using Soundscapy for Binaural Recording Analysis" = "tutorials/rendered/BinauralAnalysis.md" },
        { "How To Analyse and Represent Soundscape Perception" = "tutorials/rendered/HowToAnalyseAndRepresentSoundscapes.md" },
    ] },
    { "API Reference" = [
        { "Overview" = "reference/index.md" },
        { "Soundscapy" = "reference/soundscapy.md" },
        { "Surveys" = "reference/surveys.md" },
        { "Plotting" = [
            "reference/plotting/plotting.md",
            { "Plot Functions" = "reference/plotting/plot_functions.md" },
            { "ISO Plot" = "reference/plotting/iso_plot.md" },
            { "Likert Plot" = "reference/plotting/likert.md" },
            { "Parameter Models" = "reference/plotting/param_models.md" },
            { "Parameter Defaults" = "reference/plotting/defaults.md" },
            { "Plotting Contexts" = "reference/plotting/plot_context.md" },
        ] },
        { "SPI" = "reference/spi.md" },
        { "SATP" = "reference/satp.md" },
        { "Audio Analysis" = [
            "reference/audio/index.md",
            { "Audio Analysis" = "reference/audio/audio_analysis.md" },
            { "Metrics" = "reference/audio/metrics.md" },
            { "Binaural" = "reference/audio/binaural.md" },
            { "Parallel Processing" = "reference/audio/parallel_processing.md" },
        ] },
        { "Internals" = [
            { "Overview" = "reference/internals/index.md" },
            { "Plotting Internals" = "reference/internals/plotting-internals.md" },
            { "R Internals" = "reference/internals/r-internals.md" },
            { "Utilities" = "reference/internals/utilities.md" },
            { "Logging" = "reference/internals/logging.md" },
        ] },
    ] },
    { "Contributing" = "CONTRIBUTING.md" },
    { "News" = [
        "news.md",
        { "Upgrading from 0.7" = "migration-0.7-to-0.8.md" },
        { "Changelog" = "CHANGELOG.md" },
        { "License" = "license.md" },
    ] },
]
copyright = "&copy; 2026 Andrew Mitchell"
extra_css = [
    "https://unpkg.com/katex@0/dist/katex.min.css",
    "stylesheets/extra.css",
]
extra_javascript = [
    # "https://unpkg.com/katex@0/dist/contrib/auto-render.min.js",
    # "https://unpkg.com/katex@0/dist/katex.min.js",
    # "javascripts/katex.js",
    "javascripts/mathjax.js",
    "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js",
]
repo_name = "MitchellAcoustics/Soundscapy"
repo_url = "https://github.com/MitchellAcoustics/Soundscapy/"
site_author = "Andrew Mitchell"
site_description = "Documentation website for Soundscapy"
site_name = "Soundscapy"
site_url = "https://soundscapy.readthedocs.io/en/latest/"

[project.validation]
unresolved_references = false

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/MitchellAcoustics"

[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_section_style = "spacy"
docstring_style = "numpy"
members_order = "source"
merge_init_into_class = true
modernize_annotations = true
overloads_only = true
separate_signature = true
show_overloads = true
show_root_heading = true
show_signature = true
show_signature_annotations = true
show_signature_type_parameters = true
show_source = true
show_submodules = true
show_symbol_type_heading = true
show_symbol_type_toc = true
summary = true

[project.theme]
favicon = "img/LightLogoSmall.png"
features = [
    "content.action.edit",
    "content.action.view",
    "content.code.copy",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.path",
    "navigation.prune",
    "navigation.sections",
    "navigation.tabs",
    "navigation.top",
]
logo = "img/LightLogoSmall.png"
font.code = "Fira Code"

[project.theme.icon]
repo = "fontawesome/brands/github"

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"
