project:
  type: website

website:
  title: "Soundscapy tutorials"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - background.qmd
      - QuickStart.qmd

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true
