name: CI

on:
  workflow_call:
    outputs:
      tests-pass:
        description: "Indicates if all tests passed"
        value: ${{ github.event.inputs.tests-pass }}
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with: 
        # install a specific version of uv
        version: "0.4.29"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Setup Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install core dependencies
      run: uv sync --extra test

    - name: Run tests for core deps only
      run: uv run pytest

    - name: Install optional dependencies
      run: uv sync --all-extras

    - name: Run tests for all dependencies
      run: uv run pytest

    - name: Run tests for tutorial notebooks
      run: uv run pytest --nbmake -n=auto docs --ignore=docs/tutorials/BinauralAnalysis.ipynb --no-cov # BinauralAnalysis is too slow
    
    - name: Lint and format check
      run: |
        uv run ruff check . 
        uv run ruff format --check
