name: Documentation

on:
  workflow_call:
    outputs:
      docs-pass:
        description: "Indicates if documentation build passed"
        value: ${{ github.event.inputs.docs-pass }}
  push:
    branches:
      - main
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Cache tox
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: .tox
          key: tox-${{ hashFiles('pyproject.toml') }}

      - name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
        with:
          python-version: "3.x"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install tox
        run: python -m pip install tox
      - name: Build HTML documentation with tox
        run: tox -e docs
