name: Prek checks
on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]

concurrency:
  group: linting-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.68.0
          cache: true
          # auth-host: prefix.dev
          # auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
          frozen: true
          environments: "default"

      - name: Run Prek checks
        uses: j178/prek-action@v2
