name: Test

on:
  workflow_call:
    outputs:
      tests-pass:
        description: "Indicates if all tests passed"
        value: ${{ github.event.inputs.tests-pass }}
  push:
    branches: [ main, dev, spi-feature, simplify-optional-deps ]
  pull_request:
    branches: [ main, dev, spi-feature ]

jobs:
  lint:
    name: Lint and format check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with: 
        version: "0.4.29"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Setup Python
      run: uv python install 3.12

    - name: Lint and format check
      run: |
        uvx ruff check . 
        uvx ruff format --check

  test:
    name: Run tests with tox
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [core, audio, all]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Tox
      uses: tox-dev/gh-actions-tox@v1
      with:
        tox-env: py{310,311,312}-${{ matrix.environment }}
