name: Test

on:
  workflow_call:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [main, dev]
    paths-ignore:
      - "**.md"

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test with ${{ matrix.tasks }} on ${{ matrix.os }}

    outputs:
      tests-pass: ${{ steps.test-results.outputs.result }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        tasks: [test-import-tripwire, test-base, test-audio, test-r, test-all]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.5
        env:
          RPY2_CFFI_MODE: "ABI"

        with:
          pixi-version: v0.68.0
          environments: >-
            test test-audio test-r test-all
          cache: true
          locked: false

      - name: Run tests
        id: test-results
        run: |
          pixi run ${{ matrix.tasks }}
          echo "result=true" >> $GITHUB_OUTPUT
