name: Test

on:
  workflow_call:
    outputs:
      tests-pass:
        description: "Indicates if all tests passed"
        value: ${{ github.event.inputs.tests-pass }}
  push:
    branches: [ main, dev, spi-feature, simplify-optional-deps ]
  pull_request:
    branches: [ main, dev, spi-feature ]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint and format check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with: 
        version: "0.4.29"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Setup Python
      run: uv python install 3.12

    - name: Lint and format check
      run: |
        uvx ruff check . 
        uvx ruff format --check

  test:
    name: Test with ${{ matrix.factor }} on Python ${{ matrix.env }}
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: ["3.10", "3.11", "3.12"]
        factor: [core, audio, all]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Install tox
      run: uv tool install tox --with tox-uv --with tox-gh

    - name: Install Python
      run: uv python install ${{ matrix.env }}

    - name: Setup test suite
      run: tox --notest
      env:
        TOX_FACTORS: ${{ matrix.factor }}
        TOX_GH_MAJOR_MINOR: ${{ matrix.env }}

    - name: Run test suite
      run: tox --skip-pkg-install
      env: 
        TOX_FACTORS: ${{ matrix.factor }}
        TOX_GH_MAJOR_MINOR: ${{ matrix.env }}
